RepairSystem/Models/ServiceProvider.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepairSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public int ServiceProviderId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public decimal Price { get; set; }
        public string ContactNumber { get; set; }
        public int CategoryId { get; set; }
        public string Location { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public int ZipId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual CityZipCode CityZipCode { get; set; }
        public virtual Country Country { get; set; }
        public virtual CountryCity CountryCity { get; set; }
    }
}

RepairSystem/Controllers/ServiceProvidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RepairSystem.Models;

namespace RepairSystem.Controllers
{
    public class ServiceProvidersController : Controller
    {
        private RepairSystemEntities db = new RepairSystemEntities();

        // GET: ServiceProviders
        public ActionResult Index()
        {
            var serviceProviders = db.ServiceProviders.Include(s => s.Category).Include(s => s.CityZipCode).Include(s => s.Country).Include(s => s.CountryCity);
            return View(serviceProviders.ToList());
        }

        // GET: ServiceProviders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceProvider serviceProvider = db.ServiceProviders.Find(id);
            if (serviceProvider == null)
            {
                return HttpNotFound();
            }
            return View(serviceProvider);
        }

        // GET: ServiceProviders/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            ViewBag.ZipId = new SelectList(db.CityZipCodes, "ZipId", "ZipNumber");
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName");
            ViewBag.CityId = new SelectList(db.CountryCities, "CityId", "CityName");
            return View();
        }

        // POST: ServiceProviders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ServiceProviderId,FirstName,MiddleName,LastName,Email,Price,ContactNumber,CategoryId,Location,CountryId,CityId,ZipId")] ServiceProvider serviceProvider)
        {
            if (ModelState.IsValid)
            {
                db.ServiceProviders.Add(serviceProvider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", serviceProvider.CategoryId);
            ViewBag.ZipId = new SelectList(db.CityZipCodes, "ZipId", "ZipNumber", serviceProvider.ZipId);
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", serviceProvider.CountryId);
            ViewBag.CityId = new SelectList(db.CountryCities, "CityId", "CityName", serviceProvider.CityId);
            return View(serviceProvider);
        }

        // GET: ServiceProviders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceProvider serviceProvider = db.ServiceProviders.Find(id);
            if (serviceProvider == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", serviceProvider.CategoryId);
            ViewBag.ZipId = new SelectList(db.CityZipCodes, "ZipId", "ZipNumber", serviceProvider.ZipId);
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", serviceProvider.CountryId);
            ViewBag.CityId = new SelectList(db.CountryCities, "CityId", "CityName", serviceProvider.CityId);
            return View(serviceProvider);
        }

        // POST: ServiceProviders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ServiceProviderId,FirstName,MiddleName,LastName,Email,Price,ContactNumber,CategoryId,Location,CountryId,CityId,ZipId")] ServiceProvider serviceProvider)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceProvider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", serviceProvider.CategoryId);
            ViewBag.ZipId = new SelectList(db.CityZipCodes, "ZipId", "ZipNumber", serviceProvider.ZipId);
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", serviceProvider.CountryId);
            ViewBag.CityId = new SelectList(db.CountryCities, "CityId", "CityName", serviceProvider.CityId);
            return View(serviceProvider);
        }

        // GET: ServiceProviders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceProvider serviceProvider = db.ServiceProviders.Find(id);
            if (serviceProvider == null)
            {
                return HttpNotFound();
            }
            return View(serviceProvider);
        }

        // POST: ServiceProviders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceProvider serviceProvider = db.ServiceProviders.Find(id);
            db.ServiceProviders.Remove(serviceProvider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search()
        {
            ServiceProvider serviceProvider = new ServiceProvider();
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", serviceProvider.CategoryId);
            ViewBag.ZipId = new SelectList(db.CityZipCodes, "ZipId", "ZipNumber", serviceProvider.ZipId);
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", serviceProvider.CountryId);
            ViewBag.CityId = new SelectList(db.CountryCities, "CityId", "CityName", serviceProvider.CityId);
            return View(serviceProvider);
        }

        [HttpPost]
        public ActionResult Search(ServiceProvider serviceProvider)
        {
            var list = db.ServiceProviders.Where(x => x.CategoryId == serviceProvider.CategoryId &&
                                         x.CityId == serviceProvider.CityId &&
                                         x.CountryId == serviceProvider.CountryId &&
                                         x.ZipId == serviceProvider.ZipId
            ).ToList();
            return View("Index", list);
        }

        public JsonResult GetCities(int countryId)
        {
            var list =db.CountryCities.Where(x => x.CountryId == countryId).Select(x => new Model
            {
                Id = x.CityId,
                Name = x.CityName
            }).ToList();
            return Json(list,JsonRequestBehavior.AllowGet); ;
        }

        public JsonResult GetZips(int cityId)
        {
            var list = db.CityZipCodes.Where(x => x.CityId == cityId).Select(x => new Model
            {
                Id = x.ZipId,
                Name = x.ZipNumber
            }).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

    }
}

RepairSystem/Views/ServiceProviders/Create.cshtml
@model RepairSystem.Models.ServiceProvider

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" onload="load();">
        <h4>ServiceProvider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control",   @onchange = "loadCities();" })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, "CityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control"  ,@onchange = "loadZip();" })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipId, "ZipId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZipId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ZipId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" onclick="return validate();"/>
            </div>
        </div>
    </div>
}




<script type="text/javascript">
   


    function validate()
    {
        var error = "";
        if($("#FirstName").val()=="")
        {
            error = error + "FirstName is Required \n ";
        }
        if ($("#LastName").val() == "") {
            error = error + "LastName is Required \n ";
        }
        if ($("#Email").val() == "") {
            error = error + "Email is Required \n ";
        }
        if ($("#Price").val() == "") {
            error = error + "Price is Required \n ";
        }
        if ($("#CategoryId").val() == "") {
            error = error + "Category is Required \n ";
        }
        if ($("#Location").val() == "") {
            error = error + "Location is Required \n ";
        }
        if ($("#CountryId").val() == "") {
            error = error + "Country is Required \n ";
        }
        if ($("#CityId").val() == "") {
            error = error + "city is Required \n ";
        }
        if ($("#ZipId").val() == "") {
            error = error + "zip code is Required \n ";
        }

        if(error.length>0)
        {
            alert(error);
            return false;
        }
        return true;


    }

  

   

    function loadCities()
    {
        var countryId = $("#CountryId").val();
        $.ajax({

            url: '/ServiceProviders/GetCities',
            type: 'GET',
            data: {
                countryId:countryId
            },
            success: function (datas) {
                $("#CityId").empty();
                console.log(datas);
                $.each(datas, function (key, entry) {
                    $("#CityId").append($('<option></option>').attr('value', entry.Id).text(entry.Name));
                })
            },
            error: function (request, error) {
              
            }
        });

        loadZip();
    }


    function loadZip() {
        var cityId = $("#CityId").val();
        $.ajax({

            url: '/ServiceProviders/GetZips',
            type: 'GET',
            data: {
                cityId: cityId
            },
            success: function (datas) {
                $("#ZipId").empty();
                console.log(datas);
                $.each(datas, function (key, entry) {
                    $("#ZipId").append($('<option></option>').attr('value', entry.Id).text(entry.Name));
                })
            },
            error: function (request, error) {

            }
        });
    }

   
    $(document).ready(function () {
        load();

    });

    function load()
    {
        loadCities();
        loadZip();
    }
</script>

RepairSystem/Views/ServiceProviders/Delete.cshtml
@model RepairSystem.Models.ServiceProvider

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ServiceProvider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityZipCode.ZipNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityZipCode.ZipNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryCity.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryCity.CityName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RepairSystem/Views/ServiceProviders/Details.cshtml
@model RepairSystem.Models.ServiceProvider

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ServiceProvider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityZipCode.ZipNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityZipCode.ZipNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryCity.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryCity.CityName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ServiceProviderId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RepairSystem/Views/ServiceProviders/Edit.cshtml
@model RepairSystem.Models.ServiceProvider

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ServiceProvider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ServiceProviderId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, "CityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipId, "ZipId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZipId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ZipId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RepairSystem/Views/ServiceProviders/Search.cshtml
@model RepairSystem.Models.ServiceProvider
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>


@using (Html.BeginForm("Search", "ServiceProviders"))
{
    <div class="form-horizontal">
        <h4>ServiceProvider</h4>
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control"  ,@onchange = "loadCities();" })
                @*@Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control", @onchange = "loadZip();" })
                @*@Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZipId", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.ValidationMessageFor(model => model.ZipId, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>


    </div>
}



<script type="text/javascript">



    function loadCities() {
        var countryId = $("#CountryId").val();
        $.ajax({

            url: '/ServiceProviders/GetCities',
            type: 'GET',
            data: {
                countryId: countryId
            },
            success: function (datas) {
                $("#CityId").empty();
                console.log(datas);
                $.each(datas, function (key, entry) {
                    $("#CityId").append($('<option></option>').attr('value', entry.Id).text(entry.Name));
                })
            },
            error: function (request, error) {

            }
        });

        loadZip();
    }


    function loadZip() {
        var cityId = $("#CityId").val();
        $.ajax({

            url: '/ServiceProviders/GetZips',
            type: 'GET',
            data: {
                cityId: cityId
            },
            success: function (datas) {
                $("#ZipId").empty();
                console.log(datas);
                $.each(datas, function (key, entry) {
                    $("#ZipId").append($('<option></option>').attr('value', entry.Id).text(entry.Name));
                })
            },
            error: function (request, error) {

            }
        });
    }


    $(document).ready(function () {
        load();

    });

    function load() {
        loadCities();
        loadZip();
    }


</script>